language: rust
sudo: false

matrix:
  fast_finish: true
  include:
    - rust: 1.31.0
    - rust: stable
    - rust: beta
    - rust: nightly

    - rust: nightly
      env: RUSTFLAGS='--cfg rayon_hash_unstable'
           RUSTDOCFLAGS='--cfg rayon_hash_unstable'

branches:
  only:
    - master
    - staging
    - trying
